version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/rails
      - sqlite_data:/rails/db
    ports:
      - "80:80"
    environment:
      RAILS_ENV: production
      # in normal application RAILS_MASTER_KEY shouldn't be there, but for example we leave it there
      RAILS_MASTER_KEY: "7629d3316a7c81eb1e5f30a7855a6355"
    stdin_open: true
    tty: true
    command: ["./bin/thrust", "./bin/rails", "server"]

volumes:
  sqlite_data:
